import type { Metadata } from "next";
import Satoshi  from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.layer.css'
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import Providers from "@/components/Providers";

const satoshi = Satoshi({
  src:[{
    path: './fonts/Satoshi-Variable.woff2',
    weight: '300 900',
    style: 'normal'
  },{
    path: './fonts/Satoshi-VariableItalic.woff',
    weight: '300 900',
    style: 'italic'
  }],
  variable: '--font-satoshi',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${satoshi.variable} antialiased`}
      >
        <Providers>
          <MantineProvider>{children}</MantineProvider>
        </Providers>
      </body>
    </html>
  );
}
